#
# Copyright (C) 2021 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

# Fingerprint
TARGET_HAS_UDFPS := true

# Inherit from sm8250-common
$(call inherit-product, device/xiaomi/sm8250-common/kona.mk)

# AAPT
PRODUCT_AAPT_CONFIG := normal
PRODUCT_AAPT_PREF_CONFIG := xxhdpi

# Audio configs
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(LOCAL_PATH)/audio/,$(TARGET_COPY_OUT_VENDOR)/etc)

# Boot animation
TARGET_SCREEN_HEIGHT := 2400
TARGET_SCREEN_WIDTH := 1080

# Camera
PRODUCT_PACKAGES += \
    libMegviiFacepp-0.5.2 \
    libmegface \
    libpiex_shim

# Camera motor
PRODUCT_PACKAGES += \
    vendor.xiaomi.hardware.motor@1.0-service.xml

PRODUCT_PACKAGES += \
    vendor.xiaomi.hardware.motor@1.0.vendor

# Init
$(call soong_config_set,xiaomi_kona,variant_lib,//$(LOCAL_PATH):libvariant_xiaomi_lmi)

# Overlays
PRODUCT_PACKAGES += \
    ApertureOverlayDevice \
    FrameworkResOverlayDevice \
    LineageSDKOverlayDevice \
    LineageSystemUIOverlayDevice \
    SystemUIOverlayDevice

# Permissions
PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.sensor.barometer.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.barometer.xml

# QDCM
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(LOCAL_PATH)/qdcm/,$(TARGET_COPY_OUT_VENDOR)/etc)

# Shipping API level
PRODUCT_SHIPPING_API_LEVEL := 29

# Soong namespaces
# (wlan, wlan/qcwcn, sm8250, thermal-legacy-um, data-ipa-cfg-mgr-legacy-um
# are all added automatically by hardware/qcom-caf/common/BoardConfigQcom.mk
# now that vendor/lineage/config/BoardConfigLineage.mk is properly included
# - see BoardConfig.mk. Adding them here too caused a hard Soong conflict:
# "found in multiple namespaces" for thermal-service.qti.)
PRODUCT_SOONG_NAMESPACES += \
    $(LOCAL_PATH)

# sm8250-common/kona.mk (inherited above) assumes SoC-generic "kona"-suffixed
# vendor blob names, but lmi's own proprietary-files.txt dump uses
# device-specific "lmi"-suffixed names instead (audio.primary.lmi,
# liba2dpoffload_lmi - see vendor/xiaomi/lmi/Android.bp). Swap them.
PRODUCT_PACKAGES := $(filter-out audio.primary.kona liba2dpoffload,$(PRODUCT_PACKAGES))
PRODUCT_PACKAGES += \
    audio.primary.lmi \
    liba2dpoffload_lmi

# Inherit from vendor blobs
$(call inherit-product, vendor/xiaomi/lmi/lmi-vendor.mk)

# Extra user apps (same generator/layout as crosshatch's prebuilts/extra-apps,
# just rooted at device/xiaomi/lmi/extra-apps instead of prebuilts/extra-apps)
USER_APPS_BP := $(wildcard device/xiaomi/lmi/extra-apps/prebuilt/*.apk)
PRODUCT_PACKAGES += $(foreach apk,$(USER_APPS_BP),$(basename $(notdir $(apk))))
# .apks (bundletool APK Set, android_app_set modules) -- split-config apps like Gboard
USER_APP_SETS_BP := $(wildcard device/xiaomi/lmi/extra-apps/prebuilt/*.apks)

# KernelSUNext's bundled libksud.so never gets extracted for a pre-baked
# /product/app install -- PackageManager only extracts lib/<abi>/*.so on a
# normal /data/app install. The app execs a hardcoded path expecting that
# extraction to have happened, so ship the binary as its own copied file at
# exactly that path. Soong prebuilt module types cannot express escaping to an
# arbitrary nested product path, hence plain PRODUCT_COPY_FILES -- which needs
# BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true, set in BoardConfig.mk
# (that flag is board-scoped and is silently ignored if set from here).
# It also needs the config.fs entry to force the +x bit: PRODUCT_COPY_FILES
# copies with a plain non-preserving `cp`, and image packaging does not mirror
# the staging dir's host permissions either.
PRODUCT_COPY_FILES += \
    device/xiaomi/lmi/ksud_prebuilt/libksud.so:$(TARGET_COPY_OUT_PRODUCT)/app/KernelSUNext/lib/arm64/libksud.so \
    device/xiaomi/lmi/ksud_prebuilt/libadbroot.so:$(TARGET_COPY_OUT_PRODUCT)/app/KernelSUNext/lib/arm64/libadbroot.so
# KernelSU-Next 3.4 (kernel erofs-missing-includes, driver legacy-susfs-v2-3.4,
# UAPI 4): ksud and libadbroot.so from the 3.4.0 manager (33296). The manager
# runs `ksud install --libadbroot <nativeLibraryDir>/libadbroot.so`;
# libadbroot.so is a shared library, not exec'd, so it needs no +x.

PRODUCT_PACKAGES += $(foreach apkset,$(USER_APP_SETS_BP),$(basename $(notdir $(apkset))))
# Native libs of preinstalled apps that ship them compressed, unpacked beside
# the untouched apk (/product/app/<app>/lib/<isa>/) so the apk keeps its own
# signature and can be updated (Play, ReVanced Manager) -- the way OEM
# preinstalls do it; PackageManager never extracts a system app's libs.
# Generated by ~/extraAPKs/run.sh; the ELF copies rely on
# BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true (BoardConfig).
-include device/xiaomi/lmi/extra-apps/jni-libs.mk

# privapp-permissions-*.xml (prebuilt_etc modules) -- module name is the full
# filename including extension, unlike the .apk/.apks rules above.
USER_APP_PERMS_BP := $(wildcard device/xiaomi/lmi/extra-apps/prebuilt/privapp-permissions-*.xml)
PRODUCT_PACKAGES += $(foreach xml,$(USER_APP_PERMS_BP),$(notdir $(xml)))
