#
# Copyright (C) 2021 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

# Fingerprint
TARGET_HAS_UDFPS := true

# Inherit from sm8250-common
$(call inherit-product, device/xiaomi/sm8250-common/kona.mk)

# AAPT
PRODUCT_AAPT_CONFIG := normal
PRODUCT_AAPT_PREF_CONFIG := xxhdpi

# Audio configs
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(LOCAL_PATH)/audio/,$(TARGET_COPY_OUT_VENDOR)/etc)

# Boot animation
TARGET_SCREEN_HEIGHT := 2400
TARGET_SCREEN_WIDTH := 1080

# Camera
PRODUCT_PACKAGES += \
    libMegviiFacepp-0.5.2 \
    libmegface \
    libpiex_shim

# Camera motor
PRODUCT_PACKAGES += \
    vendor.xiaomi.hardware.motor@1.0-service.xml

PRODUCT_PACKAGES += \
    vendor.xiaomi.hardware.motor@1.0.vendor

# Init
$(call soong_config_set,xiaomi_kona,variant_lib,//$(LOCAL_PATH):libvariant_xiaomi_lmi)

# Overlays
PRODUCT_PACKAGES += \
    ApertureOverlayDevice \
    FrameworkResOverlayDevice \
    LineageSDKOverlayDevice \
    LineageSystemUIOverlayDevice \
    SystemUIOverlayDevice

# Permissions
PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.sensor.barometer.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.barometer.xml

# QDCM
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(LOCAL_PATH)/qdcm/,$(TARGET_COPY_OUT_VENDOR)/etc)

# Shipping API level
PRODUCT_SHIPPING_API_LEVEL := 29

# Soong namespaces
PRODUCT_SOONG_NAMESPACES += \
    $(LOCAL_PATH)

# Inherit from vendor blobs
$(call inherit-product, vendor/xiaomi/lmi/lmi-vendor.mk)

# Extra user apps (same generator/layout as crosshatch's prebuilts/extra-apps,
# just rooted at device/xiaomi/lmi/extra-apps instead of prebuilts/extra-apps)
USER_APPS_BP := $(wildcard device/xiaomi/lmi/extra-apps/prebuilt/*.apk)
PRODUCT_PACKAGES += $(foreach apk,$(USER_APPS_BP),$(basename $(notdir $(apk))))
# .apks (bundletool APK Set, android_app_set modules) -- split-config apps like Gboard
USER_APP_SETS_BP := $(wildcard device/xiaomi/lmi/extra-apps/prebuilt/*.apks)
PRODUCT_PACKAGES += $(foreach apkset,$(USER_APP_SETS_BP),$(basename $(notdir $(apkset))))
# Native libs of preinstalled apps that ship them compressed, unpacked beside
# the untouched apk (/product/app/<app>/lib/<isa>/) so the apk keeps its own
# signature and can be updated (Play, ReVanced Manager) -- the way OEM
# preinstalls do it; PackageManager never extracts a system app's libs.
# Generated by ~/extraAPKs/run.sh; the ELF copies rely on
# BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true (BoardConfig).
-include device/xiaomi/lmi/extra-apps/jni-libs.mk

# privapp-permissions-*.xml (prebuilt_etc modules) -- module name is the full
# filename including extension, unlike the .apk/.apks rules above.
USER_APP_PERMS_BP := $(wildcard device/xiaomi/lmi/extra-apps/prebuilt/privapp-permissions-*.xml)
PRODUCT_PACKAGES += $(foreach xml,$(USER_APP_PERMS_BP),$(notdir $(xml)))

# KernelSUNext's bundled libksud.so is never extracted for a pre-baked
# /product/app install, and the manager execs it from its native lib dir, so
# ship the binary at exactly that path. KernelSU-Next 3.4 (kernel lmi-ksu,
# UAPI 4): ksud and libadbroot.so from the 3.4.0 manager (33296); the manager
# runs `ksud install --libadbroot <nativeLibraryDir>/libadbroot.so`
# (libadbroot.so is a shared library, no +x). Needs
# BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES (BoardConfig.mk) and the
# config.fs entry for +x.
PRODUCT_COPY_FILES += \
    device/xiaomi/lmi/ksud_prebuilt/libksud.so:$(TARGET_COPY_OUT_PRODUCT)/app/KernelSUNext/lib/arm64/libksud.so \
    device/xiaomi/lmi/ksud_prebuilt/libadbroot.so:$(TARGET_COPY_OUT_PRODUCT)/app/KernelSUNext/lib/arm64/libadbroot.so

# KernelSU module autoinstall, as on sunfish/crosshatch (sunfish's KSU.md has
# the full setup). After a wipe /data/adb is empty; /product survives, so the
# ROM carries the module zips and installs them on first boot, then reboots
# once (persist.ksu_ai_reboot=1). ksu-autoinstall/ is local content:
#   NN-<name>.zip  installed once each, in filename order (no susfs module:
#                  this kernel has no susfs)
#   scripts/*.sh   boot scripts placed by ~/extraAPKs/publish.sh, run every boot
#   *.allowlist    optional: apps granted root on a wipe
#   snapshot/ksu-snapshot.tar.gz  optional finished install (make-snapshot.sh)
# init.ksu-autoinstall.rc also seeds /data/adb/ksud and runs `ksud install`, so
# KernelSU works before the manager is ever opened. Log: /data/adb/ksu-autoinstall.log
KSU_AUTOINSTALL_DIR := device/xiaomi/lmi/ksu-autoinstall
PRODUCT_COPY_FILES += \
    $(foreach z,$(wildcard $(KSU_AUTOINSTALL_DIR)/*.zip),\
        $(z):$(TARGET_COPY_OUT_PRODUCT)/etc/ksu-autoinstall/$(notdir $(z))) \
    $(foreach a,$(wildcard $(KSU_AUTOINSTALL_DIR)/*.allowlist),\
        $(a):$(TARGET_COPY_OUT_PRODUCT)/etc/ksu-autoinstall/$(notdir $(a))) \
    $(foreach s,$(wildcard $(KSU_AUTOINSTALL_DIR)/scripts/*.sh),\
        $(s):$(TARGET_COPY_OUT_PRODUCT)/etc/ksu-autoinstall/scripts/$(notdir $(s))) \
    $(foreach t,$(wildcard $(KSU_AUTOINSTALL_DIR)/snapshot/ksu-snapshot.tar.gz),\
        $(t):$(TARGET_COPY_OUT_PRODUCT)/etc/ksu-autoinstall/$(notdir $(t))) \
    device/xiaomi/lmi/ksu-snapshot.sh:$(TARGET_COPY_OUT_SYSTEM_EXT)/bin/ksu-snapshot.sh \
    device/xiaomi/lmi/ksu-autoinstall.sh:$(TARGET_COPY_OUT_SYSTEM_EXT)/bin/ksu-autoinstall.sh \
    device/xiaomi/lmi/init.ksu-autoinstall.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/init.ksu-autoinstall.rc
PRODUCT_PRODUCT_PROPERTIES += \
    persist.ksu_ai_reboot=1

# Apps installed as normal user apps once setup wizard is done, by
# install-apps.sh (in ksu-autoinstall/scripts/). They keep their own
# signature, so they update normally (File Manager+ ships this way).
USER_INSTALL_APKS := $(wildcard device/xiaomi/lmi/extra-apps/prebuilt/install-apps/*.apk)
PRODUCT_PACKAGES += $(foreach apk,$(USER_INSTALL_APKS),userapp_$(basename $(notdir $(apk))))
